spring:
  application:
    name: lab-calendar-backend
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
